### PR TITLE
Automatically rebuild Biosimulator image

### LINKED ISSUE #461: Rebuild biosimulator image on each release
We need a github action to rebuild the biosimulator image on release
https://biosimulators.org/simulators/gillespy2/

### PR DESCRIPTION
**Pull request by jtcooper10**
Issues a dispatch request to Biosim repo's workflow. Auth tokens should already have been supplied.

- Adds a simple YAML workflow to issue dispatch request.

Closes #461

### CODE REVIEW

**Review by ethangreen-dev — COMMENTED** [review]
Is there a better way than `curl` to make this API request? Otherwise, looks great!

**Comment by jtcooper10** [comment]
> Is there a better way than `curl` to make this API request? Otherwise, looks great!

I think [this GitHub Action](https://github.com/marketplace/actions/repository-dispatch) might work as an alternative? I haven't tested it yet, though.

**Comment by ethangreen-dev** [comment]
I think that's the best way to go about it. Maybe something like this? I think that's the correct workflow name -- at least, that's what's defined in `ci.yml`.

```
name: Biosimulator Rebuild
  uses: benc-uk/workflow-dispatch@v1
  with:
    workflow: Update simulator version, lint, test, compile documentation, and release
    repo: biosimulators/Biosimulators_GillesPy2
    token: ${{ secrets.PERSONAL_TOKEN }}
    inputs: "\"simulatorVersion\": \"${PACKAGE_VERSION}\", \"simulatorVersionLatest\": \"true\"}}"
```

**Comment by jtcooper10** [comment]
> I think that's the best way to go about it. Maybe something like this? I think that's the correct workflow name -- at least, that's what's defined in `ci.yml`.
> 
> ```
> name: Biosimulator Rebuild
>   uses: benc-uk/workflow-dispatch@v1
>   with:
>     workflow: Update simulator version, lint, test, compile documentation, and release
>     repo: biosimulators/Biosimulators_GillesPy2
>     token: ${{ secrets.PERSONAL_TOKEN }}
>     inputs: "\"simulatorVersion\": \"${PACKAGE_VERSION}\", \"simulatorVersionLatest\": \"true\"}}"
> ```

From looking at it, we still need to drop down into Bash to parse out the version number, and so replacing curl with that GitHub Action doesn't really end up simplifying it that much. It's probably just going to be easier to use curl as a result.

**Pull request merged**
