### PR TITLE
Improved TauHybrid with single SSA step

### LINKED ISSUE #826: Loop over integrate error in TauHybridSolver and TauHybridCSolver need to be clarified
The wording of this error message is unhelpful.  Need a pre-step check to see if the state starts the step as invalid (which can never become valid again)

### PR DESCRIPTION
**Pull request by briandrawert**
Closes #826

### CODE REVIEW

**Review by seanebum — APPROVED** [review]

**Comment by BryanRumsey** [comment]
I got the following error while testing:

## Model
Trichloroethylene

## Error
```
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
~/GillesPy2/gillespy2/solvers/numpy/tau_hybrid_solver.py in ___run(self, curr_state, curr_time, timeline, trajectory_base, initial_state, live_grapher, t, number_of_trajectories, increment, seed, debug, profile, tau_tol, event_sensitivity, integrator, integrator_options, **kwargs)
   1059         try:
-> 1060             self.__run(curr_state, curr_time, timeline, trajectory_base, initial_state, live_grapher, t,
   1061                        number_of_trajectories, increment, seed, debug,

~/GillesPy2/gillespy2/solvers/numpy/tau_hybrid_solver.py in __run(self, curr_state, curr_time, timeline, trajectory_base, initial_state, live_grapher, t, number_of_trajectories, increment, seed, debug, profile, tau_tol, event_sensitivity, integrator, integrator_options, **kwargs)
   1215                 # Run simulation to next step
-> 1216                 sol, curr_state[0], curr_time[0], save_times = self.__simulate(integrator, integrator_options,
   1217                                                                                curr_state[0], y0, curr_time[0],

~/GillesPy2/gillespy2/solvers/numpy/tau_hybrid_solver.py in __simulate(self, integrator, integrator_options, curr_state, y0, curr_time, propensities, species, parameters, compiled_reactions, active_rr, y_map, trajectory, save_times, delayed_events, trigger_states, event_sensitivity, tau_step, pure_ode, debug)
    685             if invalid_state:
--> 686                 raise Exception(f"Negative State detected in step, after single SSA step.\n\n error_message={invalid_err_message}\n curr_time={curr_time}\n tau_step={tau_step}\n curr_state={curr_state}\n\nstarting_curr_state={starting_curr_state}\n\n starting_tau_step={starting_tau_step}\nspecies_modified={species_modified}\nrxn_count={rxn_count}\n propensities={propensities}\nrxn_selected={rxn_selected}\ncompiled_reactions={compiled_reactions}\ncurr_state_after={curr_state_after} \n propensities_after={propensities_after}\nstarting_propensities={starting_propensities}\nfirst_rxn_count={first_rxn_count}\n first_err_message={first_err_message}\n 2nd_tau_step={tau_step}  ")
    687 

Exception: Negative State detected in step, after single SSA step.

 error_message='Epoxide' has negative state '-0.11879116224667463'
 curr_time=141.82018386819328
 tau_step=0.33391374203056173
 curr_state=OrderedDict([('K1', 1.125e-08), ('K2', 14.0), ('K3', 0.033), ('K4', 0.05), ('K5', 0.05), ('Dichloracatate', 5.0), ('Epoxide', -0.11879116224667463), ('Glyoxylate', 31.0), ('LossOfOneCL', 18.0), ('Output', 358.9523777821968), ('TCE', 0.0), ('J1', -1.0219200811664022), ('J2', -0.9567674499602333), ('J3', -0.167711379271723), ('J4', -1.4590898324960853), ('J5', -0.14070441955707225), ('vol', 1.0), ('t', 141.82018386819328), ('time', 141.82018386819328)])

starting_curr_state=OrderedDict([('K1', 1.125e-08), ('K2', 14.0), ('K3', 0.033), ('K4', 0.05), ('K5', 0.05), ('Dichloracatate', 4), ('Epoxide', 0.8812088377533254), ('Glyoxylate', 31), ('LossOfOneCL', 18), ('Output', 358.9523777821968), ('TCE', 0), ('J1', -1.0219200811664022), ('J2', -0.009710175437312295), ('J3', -0.23449412767783376), ('J4', -1.7596122003235837), ('J5', -0.6582707197044307), ('vol', 1.0), ('t', 141.4862701261627), ('time', 141.4862701261627)])

 starting_tau_step=0.6451612903225806
species_modified=OrderedDict([('Epoxide', True), ('Dichloracatate', True)])
rxn_count=OrderedDict([('J1', 0), ('J5', 0), ('J4', 0), ('J3', 0), ('J2', 1)])
 propensities=OrderedDict([('J1', 0.0), ('J2', 0.029079891645859737), ('J3', 0.2), ('J4', 0.9), ('J5', 1.55)])
rxn_selected=J2
compiled_reactions=OrderedDict([('J1', <code object <module> at 0x118252be0, file "<string>", line 1>), ('J5', <code object <module> at 0x118252ea0, file "<string>", line 1>), ('J4', <code object <module> at 0x118252df0, file "<string>", line 1>), ('J3', <code object <module> at 0x118252d40, file "<string>", line 1>), ('J2', <code object <module> at 0x118252c90, file "<string>", line 1>)])
curr_state_after=OrderedDict([('K1', 1.125e-08), ('K2', 14.0), ('K3', 0.033), ('K4', 0.05), ('K5', 0.05), ('Dichloracatate', 5.0), ('Epoxide', -0.11879116224667463), ('Glyoxylate', 29.0), ('LossOfOneCL', 18.0), ('Output', 360.9523777821968), ('TCE', 0.0), ('J1', -1.0219200811664022), ('J2', -0.7449754960552037), ('J3', -0.10546186961331597), ('J4', -1.1789670390332536), ('J5', -0.3636648838890415), ('vol', 1.0), ('t', 142.1314314164853), ('time', 142.1314314164853)]) 
 propensities_after=OrderedDict([('J1', 0.0), ('J2', 0.029079891645859737), ('J3', 0.2), ('J4', 0.9), ('J5', 1.55)])
starting_propensities=OrderedDict([('J1', 0.0), ('J2', 0.029079891645859737), ('J3', 0.2), ('J4', 0.9), ('J5', 1.55)])
first_rxn_count=OrderedDict([('J1', 0), ('J5', 2), ('J4', 0), ('J3', 0), ('J2', 1)])
 first_err_message='Epoxide' has negative state '-0.11879116224667463'
 2nd_tau_step=0.33391374203056173
```

**Comment by BryanRumsey** [comment]
Error encountered when `number_of_trajectories > 1`

image
image
 
This occurs in every test model I ran
```
models = [
    create_trichloroethylene, create_schlogl, create_michaelis_menten,
    create_decay, create_tyson_2_state_oscillator,
    create_vilar_oscillator, create_dimerization, create_degradation, create_robust_model,
    create_multi_firing_event, create_toggle_switch
]
```

**Comment by BryanRumsey** [comment]
Found inconsistencies between Python and C++ hybrid solvers
## Trichloroethylene
image
image


## Vilar Oscillator
image
image

**Review by BryanRumsey — CHANGES_REQUESTED** [review]
Testing notebook crashed due to excessive output

**Review by seanebum — APPROVED** [review]

**Review by seanebum — CHANGES_REQUESTED** [review]
Currently, it looks like species explicitly declared as 'continuous' are not being updated.  See hybrid events notebook or photosynthesis notebook.

**Review by BryanRumsey — APPROVED** [review]

**Review by seanebum — APPROVED** [review]

**Pull request merged**
